import '../globals.css';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export async function generateStaticParams() {
	return [{ lang: 'en-hk' }];
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}
